New mapping approach
Prominence/openweathermap-java-api pull request #41
Opened 2022-09-24 15:56 UTC by nagyesta

- Refreshes license information in file headers
- Rewrites API models to eliminate most of the custom mapping code
- Redefines API configuration options
- Simplifies fetching and mapping logic
- Updates dependency versions
- Reduces Java source level to 8 everywhere to eliminate JavaDoc warnings related to generated code
- Moves some in-line JSONs to class path resources to make tests more clean
- Adds assumptions to skip integration tests if API key is not set
- Adds assumptions to skip One Call API tests unless RUN_ONE_CALL env var is set
- Solves issue around UnsupportedOperationExceptions in certain terminators
- Adds option to use secure channel for picture URLs
- Adds new tests

Signed-off-by: Esta Nagy <nagyesta@gmail.com>

2022-09-24 16:03 UTC, nagyesta commented
Hi @Prominence ,
Finally managed to complete the fixes and rebased. I think the code is ready for review now. I am not that familiar with Cirrus CI, but it appear to me, that there was some kind of an issue after the Gradle build completed. Could you please advise how we should fix it?
Thank you in advance!

2022-09-26 19:28 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/model/generic/temperature/TemperatureValue.java
> +    @JsonIgnore
Missed test for this.

2022-09-26 19:37 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/model/roadrisk/RoadRiskModel.java
> +        return new Coordinates(coord.get(0), coord.get(1));
Missed test for this.

2022-09-26 19:38 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/model/generic/temperature/TemperatureValue.java
> +    @JsonIgnore
Fixed.

2022-09-26 19:39 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/model/roadrisk/RoadRiskModel.java
> +        return new Coordinates(coord.get(0), coord.get(1));
Fixed.

2022-09-26 20:52 UTC, nagyesta commented
> Hi @Prominence , Finally managed to complete the fixes and rebased. I think the code is ready for review now. I am not that familiar with Cirrus CI, but it appear to me, that there was some kind of an issue after the Gradle build completed. Could you please advise how we should fix it? Thank you in advance!

Never mind, it was most probably only a temporary glitch.

2022-09-29 20:52 UTC, Prominence requested changes
Please, review my comment in the previous PR. I've missed your answer, sorry.

2022-09-29 22:11 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/core/net/HttpURLConnectionBasedHttpClient.java
> +            return reader.lines().collect(Collectors.joining("\n"));
Thanks, I will fix this ASAP!

2022-09-29 22:13 UTC, nagyesta commented
> Please, review my comment in the previous PR. I've missed your answer, sorry.

No worries! I think this must be the only open question from that PR: https://github.com/Prominence/openweathermap-java-api/pull/40#discussion_r984060074
If you are fine with option 1, I can easily add it to this PR when I will fix the comment above. Alternatively, this decision can be left for a future update as well, if you are not ready to decide yet.
Either way, please let me know what to do!

2022-09-30 05:08 UTC, nagyesta commented on src/main/java/com/github/prominence/openweathermap/api/core/net/HttpURLConnectionBasedHttpClient.java
> +            return reader.lines().collect(Collectors.joining("\n"));
Done.

2022-09-30 05:12 UTC, nagyesta commented
> > Please, review my comment in the previous PR. I've missed your answer, sorry.
> 
> No worries! I think this must be the only open question from that PR: [#40 (comment)](https://github.com/Prominence/openweathermap-java-api/pull/40#discussion_r984060074) If you are fine with option 1, I can easily add it to this PR when I will fix the comment above. Alternatively, this decision can be left for a future update as well, if you are not ready to decide yet. Either way, please let me know what to do!

Based on the discussion on the other PR, I have updated the code to use option 1: `.asHTML(UnitSystem)`/ `.asJSON(UnitSystem)`/ `.asXML(UnitSystem)`. Created a shorthand as well to avoid forcing developers to always populate default values as well, so there are parameterless pairs of these methods which are only calling the longer form with `STANDARD`.

2022-09-30 20:37 UTC, Prominence approved these changes
LGTM.

Can I merge it now?

2022-09-30 21:55 UTC, nagyesta commented
Thank you for the review! Yes please, feel free to merge!

2022-09-30 21:57 UTC, merged

2022-09-30 21:58 UTC, Prominence commented
> Thank you for the review! Yes please, feel free to merge!

Do you want me to release the new version with your changes ASAP, or can I implement other API types and then release?

P.S. Big thanks for your work!

2022-09-30 22:10 UTC, nagyesta commented
Thank you, I am not in a hurry, please handle the release as you wish!