Add onecall API 3 support to allow access to daily summary
Prominence/openweathermap-java-api pull request #58
Opened 2023-11-04 16:44 UTC by dbadia

https://openweathermap.org/api/one-call-3

2023-11-08 07:06 UTC, Prominence commented
Thanks for your contribution! I'll check the changes ASAP.

2023-11-14 11:20 UTC, Prominence requested changes

2024-11-14 08:09 UTC, boblepepeur commented on src/main/java/com/github/prominence/openweathermap/api/OpenWeatherMapClient.java
> +    @SubscriptionAvailability(plans = ALL)
+1 i need to use one call api 3.0, when will you merge ?

2024-11-14 08:51 UTC, Prominence approved these changes

2024-11-14 08:52 UTC, merged

2024-11-14 08:52 UTC, Prominence commented on src/main/java/com/github/prominence/openweathermap/api/OpenWeatherMapClient.java
> +    @SubscriptionAvailability(plans = ALL)
> +1 i need to use one call api 3.0, when will you merge ?

Merged.

2024-11-14 09:45 UTC, boblepepeur commented on src/main/java/com/github/prominence/openweathermap/api/OpenWeatherMapClient.java
> +    @SubscriptionAvailability(plans = ALL)
You rocks !! Tested & Works like a charm thanksssss